<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <IsPackable>false</IsPackable>
	  <TargetFramework>net9.0</TargetFramework>
	  <LangVersion>latest</LangVersion>
	  <EnableNETAnalyzers>true</EnableNETAnalyzers>
	  <AnalysisLevel>latest</AnalysisLevel>
	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	  <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
	  <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

</Project>
